export default {
  bch: {
    priority: 100,
    isoCode: 'BCH',
    name: 'Bitcoin Cash',
    symbol: '₿',
    disambiguateSymbol: '₿CH',
    alternateSymbols: ['BCH'],
    subunit: 'Satoshi',
    subunitToUnit: 100000000,
    precision: 8,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '&#x20bf;',
    decimal: '.',
    separator: ',',
    isoNumeric: '',
    smallestDenomination: 1,
  },
  btc: {
    priority: 100,
    isoCode: 'BTC',
    name: 'Bitcoin',
    symbol: '₿',
    alternateSymbols: [],
    subunit: 'Satoshi',
    subunitToUnit: 100000000,
    precision: 8,
    symbolFirst: true,
    htmlEntity: '&#x20bf;',
    decimal: '.',
    separator: ',',
    isoNumeric: '',
    smallestDenomination: 1,
  },
  jep: {
    priority: 100,
    isoCode: 'JEP',
    name: 'Jersey Pound',
    symbol: '£',
    disambiguateSymbol: 'JEP',
    alternateSymbols: [],
    subunit: 'Penny',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#x00A3;',
    decimal: '.',
    separator: ',',
    isoNumeric: '',
    smallestDenomination: 1,
  },
  ggp: {
    priority: 100,
    isoCode: 'GGP',
    name: 'Guernsey Pound',
    symbol: '£',
    disambiguateSymbol: 'GGP',
    alternateSymbols: [],
    subunit: 'Penny',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#x00A3;',
    decimal: '.',
    separator: ',',
    isoNumeric: '',
    smallestDenomination: 1,
  },
  imp: {
    priority: 100,
    isoCode: 'IMP',
    name: 'Isle of Man Pound',
    symbol: '£',
    disambiguateSymbol: 'IMP',
    alternateSymbols: ['M£'],
    subunit: 'Penny',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#x00A3;',
    decimal: '.',
    separator: ',',
    isoNumeric: '',
    smallestDenomination: 1,
  },
  xfu: {
    priority: 100,
    isoCode: 'XFU',
    name: 'UIC Franc',
    symbol: '',
    disambiguateSymbol: 'XFU',
    alternateSymbols: [],
    subunit: '',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '',
    smallestDenomination: '',
  },
  gbx: {
    priority: 100,
    isoCode: 'GBX',
    name: 'British Penny',
    symbol: '',
    disambiguateSymbol: 'GBX',
    alternateSymbols: [],
    subunit: '',
    subunitToUnit: 1,
 precision:0,
    symbolFirst: true,
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '',
    smallestDenomination: 1,
  },
  cnh: {
    priority: 100,
    isoCode: 'CNH',
    name: 'Chinese Renminbi Yuan Offshore',
    symbol: '¥',
    disambiguateSymbol: 'CNH',
    alternateSymbols: ['CN¥', '元', 'CN元'],
    subunit: 'Fen',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '￥',
    decimal: '.',
    separator: ',',
    isoNumeric: '',
    smallestDenomination: 1,
  },
  usdc: {
    priority: 100,
    so_code: 'USDC',
    name: 'USD Coin',
    symbol: 'USDC',
    disambiguateSymbol: 'USDC',
    alternateSymbols: [],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    htmlEntity: '$',
    decimal: '.',
    separator: ',',
    isoNumeric: '',
    smallestDenomination: 1,
  },
};
