export default {
  eek: {
    priority: 100,
    isoCode: 'EEK',
    name: 'Estonian Kroon',
    symbol: 'KR',
    alternateSymbols: [],
    subunit: 'Sent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '233',
    smallestDenomination: 5,
  },
  ghc: {
    priority: 100,
    isoCode: 'GHS',
    name: 'Ghanaian Cedi',
    symbol: '₵',
    disambiguateSymbol: 'GH₵',
    alternateSymbols: ['GH₵'],
    subunit: 'Pesewa',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#x20B5;',
    decimal: '.',
    separator: ',',
    isoNumeric: '288',
    smallestDenomination: 1,
  },
  ltl: {
    priority: 100,
    isoCode: 'LTL',
    name: 'Lithuanian Litas',
    symbol: 'Lt',
    alternateSymbols: [],
    subunit: 'Centas',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '440',
    smallestDenomination: 1,
  },
  lvl: {
    priority: 100,
    isoCode: 'LVL',
    name: 'Latvian Lats',
    symbol: 'Ls',
    alternateSymbols: [],
    subunit: 'Santīms',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '428',
    smallestDenomination: 1,
  },
  mro: {
    priority: 100,
    isoCode: 'MRO',
    name: 'Mauritanian Ouguiya',
    symbol: 'UM',
    disambiguateSymbol: 'A-UM',
    alternateSymbols: [],
    subunit: 'Khoums',
    subunitToUnit: 5,
    precision: 1,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '478',
    smallestDenomination: 1,
  },
  mtl: {
    priority: 100,
    isoCode: 'MTL',
    name: 'Maltese Lira',
    symbol: '₤',
    alternateSymbols: ['Lm'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#x00A3;',
    decimal: '.',
    separator: ',',
    isoNumeric: '470',
    smallestDenomination: 1,
  },
  tmm: {
    priority: 100,
    isoCode: 'TMM',
    name: 'Turkmenistani Manat',
    symbol: 'm',
    alternateSymbols: [],
    subunit: 'Tennesi',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '795',
    smallestDenomination: 1,
  },
  yen: {
    priority: 100,
    isoCode: 'JPY',
    name: 'Japanese Yen',
    symbol: '¥',
    disambiguateSymbol: 'JPY',
    alternateSymbols: ['円', '圓'],
    subunit: 'Sen',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#x00A5;',
    decimal: '.',
    separator: ',',
    isoNumeric: '',
    smallestDenomination: 100,
  },
  zwd: {
    priority: 100,
    isoCode: 'ZWD',
    name: 'Zimbabwean Dollar',
    symbol: '$',
    disambiguateSymbol: 'ZWD',
    alternateSymbols: ['Z$'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '$',
    decimal: '.',
    separator: ',',
    isoNumeric: '716',
    smallestDenomination: 100,
  },
  zwl: {
    priority: 100,
    isoCode: 'ZWL',
    name: 'Zimbabwean Dollar',
    symbol: '$',
    disambiguateSymbol: 'ZWL',
    alternateSymbols: ['Z$'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '$',
    decimal: '.',
    separator: ',',
    isoNumeric: '932',
    smallestDenomination: 100,
  },
  zwn: {
    priority: 100,
    isoCode: 'ZWN',
    name: 'Zimbabwean Dollar',
    symbol: '$',
    disambiguateSymbol: 'ZWN',
    alternateSymbols: ['Z$'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '$',
    decimal: '.',
    separator: ',',
    isoNumeric: '942',
    smallestDenomination: 100,
  },
  zwr: {
    priority: 100,
    isoCode: 'ZWR',
    name: 'Zimbabwean Dollar',
    symbol: '$',
    disambiguateSymbol: 'ZWR',
    alternateSymbols: ['Z$'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '$',
    decimal: '.',
    separator: ',',
    isoNumeric: '935',
    smallestDenomination: 100,
  },
  vef: {
    priority: 100,
    isoCode: 'VEF',
    name: 'Venezuelan Bolívar',
    symbol: 'Bs.F',
    alternateSymbols: ['Bs'],
    subunit: 'Céntimo',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '',
    decimal: ',',
    separator: '.',
    isoNumeric: '937',
    smallestDenomination: 1,
  },
};
