export default {
  aed: {
    priority: 100,
    isoCode: 'AED',
    name: 'United Arab Emirates Dirham',
    symbol: 'د.إ',
    alternateSymbols: ['DH', 'Dhs'],
    subunit: 'Fils',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '784',
    smallestDenomination: 25,
  },
  afn: {
    priority: 100,
    isoCode: 'AFN',
    name: 'Afghan Afghani',
    symbol: '؋',
    alternateSymbols: ['Af', 'Afs'],
    subunit: 'Pul',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '971',
    smallestDenomination: 100,
  },
  all: {
    priority: 100,
    isoCode: 'ALL',
    name: 'Albanian Lek',
    symbol: 'L',
    disambiguateSymbol: 'Lek',
    alternateSymbols: ['Lek'],
    subunit: 'Qintar',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '008',
    smallestDenomination: 100,
  },
  amd: {
    priority: 100,
    isoCode: 'AMD',
    name: 'Armenian Dram',
    symbol: 'դր.',
    alternateSymbols: ['dram'],
    subunit: 'Luma',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '051',
    smallestDenomination: 10,
  },
  ang: {
    priority: 100,
    isoCode: 'ANG',
    name: 'Netherlands Antillean Gulden',
    symbol: 'ƒ',
    alternateSymbols: ['NAƒ', 'NAf', 'f'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#x0192;',
    decimal: ',',
    separator: '.',
    isoNumeric: '532',
    smallestDenomination: 1,
  },
  aoa: {
    priority: 100,
    isoCode: 'AOA',
    name: 'Angolan Kwanza',
    symbol: 'Kz',
    alternateSymbols: [],
    subunit: 'Cêntimo',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '973',
    smallestDenomination: 10,
  },
  ars: {
    priority: 100,
    isoCode: 'ARS',
    name: 'Argentine Peso',
    symbol: '$',
    disambiguateSymbol: '$m/n',
    alternateSymbols: ['$m/n', 'm$n'],
    subunit: 'Centavo',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '$',
    decimal: ',',
    separator: '.',
    isoNumeric: '032',
    smallestDenomination: 1,
  },
  aud: {
    priority: 4,
    isoCode: 'AUD',
    name: 'Australian Dollar',
    symbol: '$',
    disambiguateSymbol: 'A$',
    alternateSymbols: ['A$'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '$',
    decimal: '.',
    separator: ',',
    isoNumeric: '036',
    smallestDenomination: 5,
  },
  awg: {
    priority: 100,
    isoCode: 'AWG',
    name: 'Aruban Florin',
    symbol: 'ƒ',
    alternateSymbols: ['Afl'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '&#x0192;',
    decimal: '.',
    separator: ',',
    isoNumeric: '533',
    smallestDenomination: 5,
  },
  azn: {
    priority: 100,
    isoCode: 'AZN',
    name: 'Azerbaijani Manat',
    symbol: '₼',
    alternateSymbols: ['m', 'man'],
    subunit: 'Qəpik',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '944',
    smallestDenomination: 1,
  },
  bam: {
    priority: 100,
    isoCode: 'BAM',
    name: 'Bosnia and Herzegovina Convertible Mark',
    symbol: 'КМ',
    alternateSymbols: ['KM'],
    subunit: 'Fening',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '977',
    smallestDenomination: 5,
  },
  bbd: {
    priority: 100,
    isoCode: 'BBD',
    name: 'Barbadian Dollar',
    symbol: '$',
    disambiguateSymbol: 'Bds$',
    alternateSymbols: ['Bds$'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '$',
    decimal: '.',
    separator: ',',
    isoNumeric: '052',
    smallestDenomination: 1,
  },
  bdt: {
    priority: 100,
    isoCode: 'BDT',
    name: 'Bangladeshi Taka',
    symbol: '৳',
    alternateSymbols: ['Tk'],
    subunit: 'Paisa',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '050',
    smallestDenomination: 1,
  },
  bgn: {
    priority: 100,
    isoCode: 'BGN',
    name: 'Bulgarian Lev',
    symbol: 'лв.',
    alternateSymbols: ['lev', 'leva', 'лев', 'лева'],
    subunit: 'Stotinka',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '975',
    smallestDenomination: 1,
  },
  bhd: {
    priority: 100,
    isoCode: 'BHD',
    name: 'Bahraini Dinar',
    symbol: 'د.ب',
    alternateSymbols: ['BD'],
    subunit: 'Fils',
    subunitToUnit: 1000,
    precision: 3,
    symbolFirst: true,
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '048',
    smallestDenomination: 5,
  },
  bif: {
    priority: 100,
    isoCode: 'BIF',
    name: 'Burundian Franc',
    symbol: 'Fr',
    disambiguateSymbol: 'FBu',
    alternateSymbols: ['FBu'],
    subunit: 'Centime',
    subunitToUnit: 1,
    precision: 0,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '108',
    smallestDenomination: 100,
  },
  bmd: {
    priority: 100,
    isoCode: 'BMD',
    name: 'Bermudian Dollar',
    symbol: '$',
    disambiguateSymbol: 'BD$',
    alternateSymbols: ['BD$'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '$',
    decimal: '.',
    separator: ',',
    isoNumeric: '060',
    smallestDenomination: 1,
  },
  bnd: {
    priority: 100,
    isoCode: 'BND',
    name: 'Brunei Dollar',
    symbol: '$',
    disambiguateSymbol: 'BND',
    alternateSymbols: ['B$'],
    subunit: 'Sen',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '$',
    decimal: '.',
    separator: ',',
    isoNumeric: '096',
    smallestDenomination: 1,
  },
  bob: {
    priority: 100,
    isoCode: 'BOB',
    name: 'Bolivian Boliviano',
    symbol: 'Bs.',
    alternateSymbols: ['Bs'],
    subunit: 'Centavo',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '068',
    smallestDenomination: 10,
  },
  brl: {
    priority: 100,
    isoCode: 'BRL',
    name: 'Brazilian Real',
    symbol: 'R$',
    subunit: 'Centavo',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: 'R$',
    decimal: ',',
    separator: '.',
    isoNumeric: '986',
    smallestDenomination: 5,
  },
  bsd: {
    priority: 100,
    isoCode: 'BSD',
    name: 'Bahamian Dollar',
    symbol: '$',
    disambiguateSymbol: 'BSD',
    alternateSymbols: ['B$'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '$',
    decimal: '.',
    separator: ',',
    isoNumeric: '044',
    smallestDenomination: 1,
  },
  btn: {
    priority: 100,
    isoCode: 'BTN',
    name: 'Bhutanese Ngultrum',
    symbol: 'Nu.',
    alternateSymbols: ['Nu'],
    subunit: 'Chertrum',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '064',
    smallestDenomination: 5,
  },
  bwp: {
    priority: 100,
    isoCode: 'BWP',
    name: 'Botswana Pula',
    symbol: 'P',
    alternateSymbols: [],
    subunit: 'Thebe',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '072',
    smallestDenomination: 5,
  },
  byn: {
    priority: 100,
    isoCode: 'BYN',
    name: 'Belarusian Ruble',
    symbol: 'Br',
    disambiguateSymbol: 'BYN',
    alternateSymbols: ['бел. руб.', 'б.р.', 'руб.', 'р.'],
    subunit: 'Kapeyka',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: ',',
    separator: ' ',
    isoNumeric: '933',
    smallestDenomination: 1,
  },
  byr: {
    priority: 50,
    isoCode: 'BYR',
    name: 'Belarusian Ruble',
    symbol: 'Br',
    disambiguateSymbol: 'BYR',
    alternateSymbols: ['бел. руб.', 'б.р.', 'руб.', 'р.'],
    subunit: null,
    subunitToUnit: 1,
    precision: 0,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: ',',
    separator: ' ',
    isoNumeric: '974',
    smallestDenomination: 100,
  },
  bzd: {
    priority: 100,
    isoCode: 'BZD',
    name: 'Belize Dollar',
    symbol: '$',
    disambiguateSymbol: 'BZ$',
    alternateSymbols: ['BZ$'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '$',
    decimal: '.',
    separator: ',',
    isoNumeric: '084',
    smallestDenomination: 1,
  },
  cad: {
    priority: 5,
    isoCode: 'CAD',
    name: 'Canadian Dollar',
    symbol: '$',
    disambiguateSymbol: 'C$',
    alternateSymbols: ['C$', 'CAD$'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '$',
    decimal: '.',
    separator: ',',
    isoNumeric: '124',
    smallestDenomination: 5,
  },
  cdf: {
    priority: 100,
    isoCode: 'CDF',
    name: 'Congolese Franc',
    symbol: 'Fr',
    disambiguateSymbol: 'FC',
    alternateSymbols: ['FC'],
    subunit: 'Centime',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '976',
    smallestDenomination: 1,
  },
  chf: {
    priority: 100,
    isoCode: 'CHF',
    name: 'Swiss Franc',
    symbol: 'CHF',
    alternateSymbols: ['SFr', 'Fr'],
    subunit: 'Rappen',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    format: '%u%n',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '756',
    smallestDenomination: 5,
  },
  clf: {
    priority: 100,
    isoCode: 'CLF',
    name: 'Unidad de Fomento',
    symbol: 'UF',
    alternateSymbols: [],
    subunit: 'Peso',
    subunitToUnit: 10000,
    precision: 4,
    symbolFirst: true,
    htmlEntity: '&#x20B1;',
    decimal: ',',
    separator: '.',
    isoNumeric: '990',
  },
  clp: {
    priority: 100,
    isoCode: 'CLP',
    name: 'Chilean Peso',
    symbol: '$',
    disambiguateSymbol: 'CLP',
    alternateSymbols: [],
    subunit: 'Peso',
    subunitToUnit: 1,
    precision: 0,
    symbolFirst: true,
    htmlEntity: '&#36;',
    decimal: ',',
    separator: '.',
    isoNumeric: '152',
    smallestDenomination: 1,
  },
  cny: {
    priority: 100,
    isoCode: 'CNY',
    name: 'Chinese Renminbi Yuan',
    symbol: '¥',
    alternateSymbols: ['CN¥', '元', 'CN元'],
    subunit: 'Fen',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '￥',
    decimal: '.',
    separator: ',',
    isoNumeric: '156',
    smallestDenomination: 1,
  },
  cop: {
    priority: 100,
    isoCode: 'COP',
    name: 'Colombian Peso',
    symbol: '$',
    disambiguateSymbol: 'COL$',
    alternateSymbols: ['COL$'],
    subunit: 'Centavo',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#36;',
    decimal: ',',
    separator: '.',
    isoNumeric: '170',
    smallestDenomination: 20,
  },
  crc: {
    priority: 100,
    isoCode: 'CRC',
    name: 'Costa Rican Colón',
    symbol: '₡',
    alternateSymbols: ['¢'],
    subunit: 'Céntimo',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#x20A1;',
    decimal: ',',
    separator: '.',
    isoNumeric: '188',
    smallestDenomination: 500,
  },
  cuc: {
    priority: 100,
    isoCode: 'CUC',
    name: 'Cuban Convertible Peso',
    symbol: '$',
    disambiguateSymbol: 'CUC$',
    alternateSymbols: ['CUC$'],
    subunit: 'Centavo',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '931',
    smallestDenomination: 1,
  },
  cup: {
    priority: 100,
    isoCode: 'CUP',
    name: 'Cuban Peso',
    symbol: '$',
    disambiguateSymbol: '$MN',
    alternateSymbols: ['$MN'],
    subunit: 'Centavo',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#x20B1;',
    decimal: '.',
    separator: ',',
    isoNumeric: '192',
    smallestDenomination: 1,
  },
  cve: {
    priority: 100,
    isoCode: 'CVE',
    name: 'Cape Verdean Escudo',
    symbol: '$',
    disambiguateSymbol: 'Esc',
    alternateSymbols: ['Esc'],
    subunit: 'Centavo',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '132',
    smallestDenomination: 100,
  },
  czk: {
    priority: 100,
    isoCode: 'CZK',
    name: 'Czech Koruna',
    symbol: 'Kč',
    alternateSymbols: [],
    subunit: 'Haléř',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: ',',
    separator: ' ',
    isoNumeric: '203',
    smallestDenomination: 100,
  },
  djf: {
    priority: 100,
    isoCode: 'DJF',
    name: 'Djiboutian Franc',
    symbol: 'Fdj',
    alternateSymbols: [],
    subunit: 'Centime',
    subunitToUnit: 1,
    precision: 0,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '262',
    smallestDenomination: 100,
  },
  dkk: {
    priority: 100,
    isoCode: 'DKK',
    name: 'Danish Krone',
    symbol: 'kr.',
    disambiguateSymbol: 'DKK',
    alternateSymbols: [',-'],
    subunit: 'Øre',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: ',',
    separator: '.',
    isoNumeric: '208',
    smallestDenomination: 50,
  },
  dop: {
    priority: 100,
    isoCode: 'DOP',
    name: 'Dominican Peso',
    symbol: '$',
    disambiguateSymbol: 'RD$',
    alternateSymbols: ['RD$'],
    subunit: 'Centavo',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#x20B1;',
    decimal: '.',
    separator: ',',
    isoNumeric: '214',
    smallestDenomination: 100,
  },
  dzd: {
    priority: 100,
    isoCode: 'DZD',
    name: 'Algerian Dinar',
    symbol: 'د.ج',
    alternateSymbols: ['DA'],
    subunit: 'Centime',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '012',
    smallestDenomination: 100,
  },
  egp: {
    priority: 100,
    isoCode: 'EGP',
    name: 'Egyptian Pound',
    symbol: 'ج.م',
    alternateSymbols: ['LE', 'E£', 'L.E.'],
    subunit: 'Piastre',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#x00A3;',
    decimal: '.',
    separator: ',',
    isoNumeric: '818',
    smallestDenomination: 25,
  },
  ern: {
    priority: 100,
    isoCode: 'ERN',
    name: 'Eritrean Nakfa',
    symbol: 'Nfk',
    alternateSymbols: [],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '232',
    smallestDenomination: 1,
  },
  etb: {
    priority: 100,
    isoCode: 'ETB',
    name: 'Ethiopian Birr',
    symbol: 'Br',
    disambiguateSymbol: 'ETB',
    alternateSymbols: [],
    subunit: 'Santim',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '230',
    smallestDenomination: 1,
  },
  eur: {
    priority: 2,
    isoCode: 'EUR',
    name: 'Euro',
    symbol: '€',
    alternateSymbols: [],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#x20AC;',
    decimal: ',',
    separator: '.',
    isoNumeric: '978',
    smallestDenomination: 1,
  },
  fjd: {
    priority: 100,
    isoCode: 'FJD',
    name: 'Fijian Dollar',
    symbol: '$',
    disambiguateSymbol: 'FJ$',
    alternateSymbols: ['FJ$'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '$',
    decimal: '.',
    separator: ',',
    isoNumeric: '242',
    smallestDenomination: 5,
  },
  fkp: {
    priority: 100,
    isoCode: 'FKP',
    name: 'Falkland Pound',
    symbol: '£',
    disambiguateSymbol: 'FK£',
    alternateSymbols: ['FK£'],
    subunit: 'Penny',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '&#x00A3;',
    decimal: '.',
    separator: ',',
    isoNumeric: '238',
    smallestDenomination: 1,
  },
  gbp: {
    priority: 3,
    isoCode: 'GBP',
    name: 'British Pound',
    symbol: '£',
    alternateSymbols: [],
    subunit: 'Penny',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#x00A3;',
    decimal: '.',
    separator: ',',
    isoNumeric: '826',
    smallestDenomination: 1,
  },
  gel: {
    priority: 100,
    isoCode: 'GEL',
    name: 'Georgian Lari',
    symbol: 'ლ',
    alternateSymbols: ['lari'],
    subunit: 'Tetri',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '981',
    smallestDenomination: 1,
  },
  ghs: {
    priority: 100,
    isoCode: 'GHS',
    name: 'Ghanaian Cedi',
    symbol: '₵',
    alternateSymbols: ['GH¢', 'GH₵'],
    subunit: 'Pesewa',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#x20B5;',
    decimal: '.',
    separator: ',',
    isoNumeric: '936',
    smallestDenomination: 1,
  },
  gip: {
    priority: 100,
    isoCode: 'GIP',
    name: 'Gibraltar Pound',
    symbol: '£',
    disambiguateSymbol: 'GIP',
    alternateSymbols: [],
    subunit: 'Penny',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#x00A3;',
    decimal: '.',
    separator: ',',
    isoNumeric: '292',
    smallestDenomination: 1,
  },
  gmd: {
    priority: 100,
    isoCode: 'GMD',
    name: 'Gambian Dalasi',
    symbol: 'D',
    alternateSymbols: [],
    subunit: 'Butut',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '270',
    smallestDenomination: 1,
  },
  gnf: {
    priority: 100,
    isoCode: 'GNF',
    name: 'Guinean Franc',
    symbol: 'Fr',
    disambiguateSymbol: 'FG',
    alternateSymbols: ['FG', 'GFr'],
    subunit: 'Centime',
    subunitToUnit: 1,
    precision: 0,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '324',
    smallestDenomination: 100,
  },
  gtq: {
    priority: 100,
    isoCode: 'GTQ',
    name: 'Guatemalan Quetzal',
    symbol: 'Q',
    alternateSymbols: [],
    subunit: 'Centavo',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '320',
    smallestDenomination: 1,
  },
  gyd: {
    priority: 100,
    isoCode: 'GYD',
    name: 'Guyanese Dollar',
    symbol: '$',
    disambiguateSymbol: 'G$',
    alternateSymbols: ['G$'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '$',
    decimal: '.',
    separator: ',',
    isoNumeric: '328',
    smallestDenomination: 100,
  },
  hkd: {
    priority: 100,
    isoCode: 'HKD',
    name: 'Hong Kong Dollar',
    symbol: '$',
    disambiguateSymbol: 'HK$',
    alternateSymbols: ['HK$'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '$',
    decimal: '.',
    separator: ',',
    isoNumeric: '344',
    smallestDenomination: 10,
  },
  hnl: {
    priority: 100,
    isoCode: 'HNL',
    name: 'Honduran Lempira',
    symbol: 'L',
    disambiguateSymbol: 'HNL',
    alternateSymbols: [],
    subunit: 'Centavo',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '340',
    smallestDenomination: 5,
  },
  hrk: {
    priority: 100,
    isoCode: 'HRK',
    name: 'Croatian Kuna',
    symbol: 'kn',
    alternateSymbols: [],
    subunit: 'Lipa',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: ',',
    separator: '.',
    isoNumeric: '191',
    smallestDenomination: 1,
  },
  htg: {
    priority: 100,
    isoCode: 'HTG',
    name: 'Haitian Gourde',
    symbol: 'G',
    alternateSymbols: [],
    subunit: 'Centime',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '332',
    smallestDenomination: 5,
  },
  huf: {
    priority: 100,
    isoCode: 'HUF',
    name: 'Hungarian Forint',
    symbol: 'Ft',
    alternateSymbols: [],
    subunit: '',
    subunitToUnit: 1,
    precision: 0,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: ',',
    separator: ' ',
    isoNumeric: '348',
    smallestDenomination: 5,
  },
  idr: {
    priority: 100,
    isoCode: 'IDR',
    name: 'Indonesian Rupiah',
    symbol: 'Rp',
    alternateSymbols: [],
    subunit: 'Sen',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '',
    decimal: ',',
    separator: '.',
    isoNumeric: '360',
    smallestDenomination: 5000,
  },
  ils: {
    priority: 100,
    isoCode: 'ILS',
    name: 'Israeli New Sheqel',
    symbol: '₪',
    alternateSymbols: ['ש״ח', 'NIS'],
    subunit: 'Agora',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#x20AA;',
    decimal: '.',
    separator: ',',
    isoNumeric: '376',
    smallestDenomination: 10,
  },
  inr: {
    priority: 100,
    isoCode: 'INR',
    name: 'Indian Rupee',
    symbol: '₹',
    alternateSymbols: ['Rs', '৳', '૱', '௹', 'रु', '₨'],
    subunit: 'Paisa',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#x20b9;',
    decimal: '.',
    separator: ',',
    isoNumeric: '356',
    smallestDenomination: 50,
  },
  iqd: {
    priority: 100,
    isoCode: 'IQD',
    name: 'Iraqi Dinar',
    symbol: 'ع.د',
    alternateSymbols: [],
    subunit: 'Fils',
    subunitToUnit: 1000,
    precision: 3,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '368',
    smallestDenomination: 50000,
  },
  irr: {
    priority: 100,
    isoCode: 'IRR',
    name: 'Iranian Rial',
    symbol: '﷼',
    alternateSymbols: [],
    subunit: null,
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#xFDFC;',
    decimal: '.',
    separator: ',',
    isoNumeric: '364',
    smallestDenomination: 5000,
  },
  isk: {
    priority: 100,
    isoCode: 'ISK',
    name: 'Icelandic Króna',
    symbol: 'kr.',
    alternateSymbols: ['Íkr'],
    subunit: null,
    subunitToUnit: 1,
    precision: 0,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: ',',
    separator: '.',
    isoNumeric: '352',
    smallestDenomination: 1,
  },
  jmd: {
    priority: 100,
    isoCode: 'JMD',
    name: 'Jamaican Dollar',
    symbol: '$',
    disambiguateSymbol: 'J$',
    alternateSymbols: ['J$'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '$',
    decimal: '.',
    separator: ',',
    isoNumeric: '388',
    smallestDenomination: 1,
  },
  jod: {
    priority: 100,
    isoCode: 'JOD',
    name: 'Jordanian Dinar',
    symbol: 'د.ا',
    alternateSymbols: ['JD'],
    subunit: 'Fils',
    subunitToUnit: 1000,
    precision: 3,
    symbolFirst: true,
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '400',
    smallestDenomination: 5,
  },
  jpy: {
    priority: 6,
    isoCode: 'JPY',
    name: 'Japanese Yen',
    symbol: '¥',
    alternateSymbols: ['円', '圓'],
    subunit: null,
    subunitToUnit: 1,
    precision: 0,
    symbolFirst: true,
    htmlEntity: '&#x00A5;',
    decimal: '.',
    separator: ',',
    isoNumeric: '392',
    smallestDenomination: 1,
  },
  kes: {
    priority: 100,
    isoCode: 'KES',
    name: 'Kenyan Shilling',
    symbol: 'KSh',
    alternateSymbols: ['Sh'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '404',
    smallestDenomination: 50,
  },
  kgs: {
    priority: 100,
    isoCode: 'KGS',
    name: 'Kyrgyzstani Som',
    symbol: 'som',
    alternateSymbols: ['сом'],
    subunit: 'Tyiyn',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '417',
    smallestDenomination: 1,
  },
  khr: {
    priority: 100,
    isoCode: 'KHR',
    name: 'Cambodian Riel',
    symbol: '៛',
    alternateSymbols: [],
    subunit: 'Sen',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '&#x17DB;',
    decimal: '.',
    separator: ',',
    isoNumeric: '116',
    smallestDenomination: 5000,
  },
  kmf: {
    priority: 100,
    isoCode: 'KMF',
    name: 'Comorian Franc',
    symbol: 'Fr',
    disambiguateSymbol: 'CF',
    alternateSymbols: ['CF'],
    subunit: 'Centime',
    subunitToUnit: 1,
    precision: 0,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '174',
    smallestDenomination: 100,
  },
  kpw: {
    priority: 100,
    isoCode: 'KPW',
    name: 'North Korean Won',
    symbol: '₩',
    alternateSymbols: [],
    subunit: 'Chŏn',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '&#x20A9;',
    decimal: '.',
    separator: ',',
    isoNumeric: '408',
    smallestDenomination: 1,
  },
  krw: {
    priority: 100,
    isoCode: 'KRW',
    name: 'South Korean Won',
    symbol: '₩',
    subunit: null,
    subunitToUnit: 1,
    precision: 0,
    alternateSymbols: [],
    symbolFirst: true,
    htmlEntity: '&#x20A9;',
    decimal: '.',
    separator: ',',
    isoNumeric: '410',
    smallestDenomination: 1,
  },
  kwd: {
    priority: 100,
    isoCode: 'KWD',
    name: 'Kuwaiti Dinar',
    symbol: 'د.ك',
    alternateSymbols: ['K.D.'],
    subunit: 'Fils',
    subunitToUnit: 1000,
    precision: 3,
    symbolFirst: true,
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '414',
    smallestDenomination: 5,
  },
  kyd: {
    priority: 100,
    isoCode: 'KYD',
    name: 'Cayman Islands Dollar',
    symbol: '$',
    disambiguateSymbol: 'CI$',
    alternateSymbols: ['CI$'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '$',
    decimal: '.',
    separator: ',',
    isoNumeric: '136',
    smallestDenomination: 1,
  },
  kzt: {
    priority: 100,
    isoCode: 'KZT',
    name: 'Kazakhstani Tenge',
    symbol: '₸',
    alternateSymbols: [],
    subunit: 'Tiyn',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '398',
    smallestDenomination: 100,
  },
  lak: {
    priority: 100,
    isoCode: 'LAK',
    name: 'Lao Kip',
    symbol: '₭',
    alternateSymbols: ['₭N'],
    subunit: 'Att',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '&#x20AD;',
    decimal: '.',
    separator: ',',
    isoNumeric: '418',
    smallestDenomination: 10,
  },
  lbp: {
    priority: 100,
    isoCode: 'LBP',
    name: 'Lebanese Pound',
    symbol: 'ل.ل',
    alternateSymbols: ['£', 'L£'],
    subunit: 'Piastre',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#x00A3;',
    decimal: '.',
    separator: ',',
    isoNumeric: '422',
    smallestDenomination: 25000,
  },
  lkr: {
    priority: 100,
    isoCode: 'LKR',
    name: 'Sri Lankan Rupee',
    symbol: '₨',
    disambiguateSymbol: 'SLRs',
    alternateSymbols: ['රු', 'ரூ', 'SLRs', '/-'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '&#8360;',
    decimal: '.',
    separator: ',',
    isoNumeric: '144',
    smallestDenomination: 100,
  },
  lrd: {
    priority: 100,
    isoCode: 'LRD',
    name: 'Liberian Dollar',
    symbol: '$',
    disambiguateSymbol: 'L$',
    alternateSymbols: ['L$'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '$',
    decimal: '.',
    separator: ',',
    isoNumeric: '430',
    smallestDenomination: 5,
  },
  lsl: {
    priority: 100,
    isoCode: 'LSL',
    name: 'Lesotho Loti',
    symbol: 'L',
    disambiguateSymbol: 'M',
    alternateSymbols: ['M'],
    subunit: 'Sente',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '426',
    smallestDenomination: 1,
  },
  lyd: {
    priority: 100,
    isoCode: 'LYD',
    name: 'Libyan Dinar',
    symbol: 'ل.د',
    alternateSymbols: ['LD'],
    subunit: 'Dirham',
    subunitToUnit: 1000,
    precision: 3,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '434',
    smallestDenomination: 50,
  },
  mad: {
    priority: 100,
    isoCode: 'MAD',
    name: 'Moroccan Dirham',
    symbol: 'د.م.',
    alternateSymbols: [],
    subunit: 'Centime',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '504',
    smallestDenomination: 1,
  },
  mdl: {
    priority: 100,
    isoCode: 'MDL',
    name: 'Moldovan Leu',
    symbol: 'L',
    alternateSymbols: ['lei'],
    subunit: 'Ban',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '498',
    smallestDenomination: 1,
  },
  mga: {
    priority: 100,
    isoCode: 'MGA',
    name: 'Malagasy Ariary',
    symbol: 'Ar',
    alternateSymbols: [],
    subunit: 'Iraimbilanja',
    subunitToUnit: 5,
precision: 1,
    symbolFirst: true,
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '969',
    smallestDenomination: 1,
  },
  mkd: {
    priority: 100,
    isoCode: 'MKD',
    name: 'Macedonian Denar',
    symbol: 'ден',
    alternateSymbols: [],
    subunit: 'Deni',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '807',
    smallestDenomination: 100,
  },
  mmk: {
    priority: 100,
    isoCode: 'MMK',
    name: 'Myanmar Kyat',
    symbol: 'K',
    disambiguateSymbol: 'MMK',
    alternateSymbols: [],
    subunit: 'Pya',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '104',
    smallestDenomination: 50,
  },
  mnt: {
    priority: 100,
    isoCode: 'MNT',
    name: 'Mongolian Tögrög',
    symbol: '₮',
    alternateSymbols: [],
    subunit: 'Möngö',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '&#x20AE;',
    decimal: '.',
    separator: ',',
    isoNumeric: '496',
    smallestDenomination: 2000,
  },
  mop: {
    priority: 100,
    isoCode: 'MOP',
    name: 'Macanese Pataca',
    symbol: 'P',
    alternateSymbols: ['MOP$'],
    subunit: 'Avo',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '446',
    smallestDenomination: 10,
  },
  mru: {
    priority: 100,
    isoCode: 'MRU',
    name: 'Mauritanian Ouguiya',
    symbol: 'UM',
    alternateSymbols: [],
    subunit: 'Khoums',
    subunitToUnit: 5,
precision: 1,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '929',
    smallestDenomination: 1,
  },
  mur: {
    priority: 100,
    isoCode: 'MUR',
    name: 'Mauritian Rupee',
    symbol: '₨',
    alternateSymbols: [],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#x20A8;',
    decimal: '.',
    separator: ',',
    isoNumeric: '480',
    smallestDenomination: 100,
  },
  mvr: {
    priority: 100,
    isoCode: 'MVR',
    name: 'Maldivian Rufiyaa',
    symbol: 'MVR',
    alternateSymbols: ['MRF', 'Rf', '/-', 'ރ'],
    subunit: 'Laari',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '462',
    smallestDenomination: 1,
  },
  mwk: {
    priority: 100,
    isoCode: 'MWK',
    name: 'Malawian Kwacha',
    symbol: 'MK',
    alternateSymbols: [],
    subunit: 'Tambala',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '454',
    smallestDenomination: 1,
  },
  mxn: {
    priority: 100,
    isoCode: 'MXN',
    name: 'Mexican Peso',
    symbol: '$',
    disambiguateSymbol: 'MEX$',
    alternateSymbols: ['MEX$'],
    subunit: 'Centavo',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '$',
    decimal: '.',
    separator: ',',
    isoNumeric: '484',
    smallestDenomination: 5,
  },
  myr: {
    priority: 100,
    isoCode: 'MYR',
    name: 'Malaysian Ringgit',
    symbol: 'RM',
    alternateSymbols: [],
    subunit: 'Sen',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '458',
    smallestDenomination: 5,
  },
  mzn: {
    priority: 100,
    isoCode: 'MZN',
    name: 'Mozambican Metical',
    symbol: 'MTn',
    alternateSymbols: ['MZN'],
    subunit: 'Centavo',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '',
    decimal: ',',
    separator: '.',
    isoNumeric: '943',
    smallestDenomination: 1,
  },
  nad: {
    priority: 100,
    isoCode: 'NAD',
    name: 'Namibian Dollar',
    symbol: '$',
    disambiguateSymbol: 'N$',
    alternateSymbols: ['N$'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '$',
    decimal: '.',
    separator: ',',
    isoNumeric: '516',
    smallestDenomination: 5,
  },
  ngn: {
    priority: 100,
    isoCode: 'NGN',
    name: 'Nigerian Naira',
    symbol: '₦',
    alternateSymbols: [],
    subunit: 'Kobo',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#x20A6;',
    decimal: '.',
    separator: ',',
    isoNumeric: '566',
    smallestDenomination: 50,
  },
  nio: {
    priority: 100,
    isoCode: 'NIO',
    name: 'Nicaraguan Córdoba',
    symbol: 'C$',
    disambiguateSymbol: 'NIO$',
    alternateSymbols: [],
    subunit: 'Centavo',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '558',
    smallestDenomination: 5,
  },
  nok: {
    priority: 100,
    isoCode: 'NOK',
    name: 'Norwegian Krone',
    symbol: 'kr',
    disambiguateSymbol: 'NOK',
    alternateSymbols: [',-'],
    subunit: 'Øre',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: 'kr',
    decimal: ',',
    separator: '.',
    isoNumeric: '578',
    smallestDenomination: 100,
  },
  npr: {
    priority: 100,
    isoCode: 'NPR',
    name: 'Nepalese Rupee',
    symbol: 'Rs.',
    disambiguateSymbol: 'NPR',
    alternateSymbols: ['Rs', 'रू', '₨'],
    subunit: 'Paisa',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#x20A8;',
    decimal: '.',
    separator: ',',
    isoNumeric: '524',
    smallestDenomination: 1,
  },
  nzd: {
    priority: 100,
    isoCode: 'NZD',
    name: 'New Zealand Dollar',
    symbol: '$',
    disambiguateSymbol: 'NZ$',
    alternateSymbols: ['NZ$'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '$',
    decimal: '.',
    separator: ',',
    isoNumeric: '554',
    smallestDenomination: 10,
  },
  omr: {
    priority: 100,
    isoCode: 'OMR',
    name: 'Omani Rial',
    symbol: 'ر.ع.',
    alternateSymbols: [],
    subunit: 'Baisa',
    subunitToUnit: 1000,
    precision: 3,
    symbolFirst: true,
    htmlEntity: '&#xFDFC;',
    decimal: '.',
    separator: ',',
    isoNumeric: '512',
    smallestDenomination: 5,
  },
  pab: {
    priority: 100,
    isoCode: 'PAB',
    name: 'Panamanian Balboa',
    symbol: 'B/.',
    alternateSymbols: [],
    subunit: 'Centésimo',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '590',
    smallestDenomination: 1,
  },
  pen: {
    priority: 100,
    isoCode: 'PEN',
    name: 'Peruvian Sol',
    symbol: 'S/',
    alternateSymbols: [],
    subunit: 'Céntimo',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: 'S/',
    decimal: '.',
    separator: ',',
    isoNumeric: '604',
    smallestDenomination: 1,
  },
  pgk: {
    priority: 100,
    isoCode: 'PGK',
    name: 'Papua New Guinean Kina',
    symbol: 'K',
    disambiguateSymbol: 'PGK',
    alternateSymbols: [],
    subunit: 'Toea',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '598',
    smallestDenomination: 5,
  },
  php: {
    priority: 100,
    isoCode: 'PHP',
    name: 'Philippine Peso',
    symbol: '₱',
    alternateSymbols: ['PHP', 'PhP', 'P'],
    subunit: 'Centavo',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#x20B1;',
    decimal: '.',
    separator: ',',
    isoNumeric: '608',
    smallestDenomination: 1,
  },
  pkr: {
    priority: 100,
    isoCode: 'PKR',
    name: 'Pakistani Rupee',
    symbol: '₨',
    disambiguateSymbol: 'PKR',
    alternateSymbols: ['Rs'],
    subunit: 'Paisa',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#x20A8;',
    decimal: '.',
    separator: ',',
    isoNumeric: '586',
    smallestDenomination: 100,
  },
  pln: {
    priority: 100,
    isoCode: 'PLN',
    name: 'Polish Złoty',
    symbol: 'zł',
    alternateSymbols: [],
    subunit: 'Grosz',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: 'z&#322;',
    decimal: ',',
    separator: ' ',
    isoNumeric: '985',
    smallestDenomination: 1,
  },
  pyg: {
    priority: 100,
    isoCode: 'PYG',
    name: 'Paraguayan Guaraní',
    symbol: '₲',
    alternateSymbols: [],
    subunit: 'Céntimo',
    subunitToUnit: 1,
    precision: 0,
    symbolFirst: true,
    htmlEntity: '&#x20B2;',
    decimal: '.',
    separator: ',',
    isoNumeric: '600',
    smallestDenomination: 5000,
  },
  qar: {
    priority: 100,
    isoCode: 'QAR',
    name: 'Qatari Riyal',
    symbol: 'ر.ق',
    alternateSymbols: ['QR'],
    subunit: 'Dirham',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '&#xFDFC;',
    decimal: '.',
    separator: ',',
    isoNumeric: '634',
    smallestDenomination: 1,
  },
  ron: {
    priority: 100,
    isoCode: 'RON',
    name: 'Romanian Leu',
    symbol: 'Lei',
    alternateSymbols: [],
    subunit: 'Bani',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: ',',
    separator: '.',
    isoNumeric: '946',
    smallestDenomination: 1,
  },
  rsd: {
    priority: 100,
    isoCode: 'RSD',
    name: 'Serbian Dinar',
    symbol: 'РСД',
    alternateSymbols: ['RSD', 'din', 'дин'],
    subunit: 'Para',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '941',
    smallestDenomination: 100,
  },
  rub: {
    priority: 100,
    isoCode: 'RUB',
    name: 'Russian Ruble',
    symbol: '₽',
    alternateSymbols: ['руб.', 'р.'],
    subunit: 'Kopeck',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '&#x20BD;',
    decimal: ',',
    separator: '.',
    isoNumeric: '643',
    smallestDenomination: 1,
  },
  rwf: {
    priority: 100,
    isoCode: 'RWF',
    name: 'Rwandan Franc',
    symbol: 'FRw',
    alternateSymbols: ['RF', 'R₣'],
    subunit: 'Centime',
    subunitToUnit: 1,
    precision: 0,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '646',
    smallestDenomination: 100,
  },
  sar: {
    priority: 100,
    isoCode: 'SAR',
    name: 'Saudi Riyal',
    symbol: 'ر.س',
    alternateSymbols: ['SR', '﷼'],
    subunit: 'Hallallah',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#xFDFC;',
    decimal: '.',
    separator: ',',
    isoNumeric: '682',
    smallestDenomination: 5,
  },
  sbd: {
    priority: 100,
    isoCode: 'SBD',
    name: 'Solomon Islands Dollar',
    symbol: '$',
    disambiguateSymbol: 'SI$',
    alternateSymbols: ['SI$'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '$',
    decimal: '.',
    separator: ',',
    isoNumeric: '090',
    smallestDenomination: 10,
  },
  scr: {
    priority: 100,
    isoCode: 'SCR',
    name: 'Seychellois Rupee',
    symbol: '₨',
    disambiguateSymbol: 'SRe',
    alternateSymbols: ['SRe', 'SR'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '&#x20A8;',
    decimal: '.',
    separator: ',',
    isoNumeric: '690',
    smallestDenomination: 1,
  },
  sdg: {
    priority: 100,
    isoCode: 'SDG',
    name: 'Sudanese Pound',
    symbol: '£',
    disambiguateSymbol: 'SDG',
    alternateSymbols: [],
    subunit: 'Piastre',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '938',
    smallestDenomination: 1,
  },
  sek: {
    priority: 100,
    isoCode: 'SEK',
    name: 'Swedish Krona',
    symbol: 'kr',
    disambiguateSymbol: 'SEK',
    alternateSymbols: [':-'],
    subunit: 'Öre',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: ',',
    separator: ' ',
    isoNumeric: '752',
    smallestDenomination: 100,
  },
  sgd: {
    priority: 100,
    isoCode: 'SGD',
    name: 'Singapore Dollar',
    symbol: '$',
    disambiguateSymbol: 'S$',
    alternateSymbols: ['S$'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '$',
    decimal: '.',
    separator: ',',
    isoNumeric: '702',
    smallestDenomination: 1,
  },
  shp: {
    priority: 100,
    isoCode: 'SHP',
    name: 'Saint Helenian Pound',
    symbol: '£',
    disambiguateSymbol: 'SHP',
    alternateSymbols: [],
    subunit: 'Penny',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '&#x00A3;',
    decimal: '.',
    separator: ',',
    isoNumeric: '654',
    smallestDenomination: 1,
  },
  skk: {
    priority: 100,
    isoCode: 'SKK',
    name: 'Slovak Koruna',
    symbol: 'Sk',
    alternateSymbols: [],
    subunit: 'Halier',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '703',
    smallestDenomination: 50,
  },
  sll: {
    priority: 100,
    isoCode: 'SLL',
    name: 'Sierra Leonean Leone',
    symbol: 'Le',
    alternateSymbols: [],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '694',
    smallestDenomination: 1000,
  },
  sos: {
    priority: 100,
    isoCode: 'SOS',
    name: 'Somali Shilling',
    symbol: 'Sh',
    alternateSymbols: ['Sh.So'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '706',
    smallestDenomination: 1,
  },
  srd: {
    priority: 100,
    isoCode: 'SRD',
    name: 'Surinamese Dollar',
    symbol: '$',
    disambiguateSymbol: 'SRD',
    alternateSymbols: [],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '968',
    smallestDenomination: 1,
  },
  ssp: {
    priority: 100,
    isoCode: 'SSP',
    name: 'South Sudanese Pound',
    symbol: '£',
    disambiguateSymbol: 'SSP',
    alternateSymbols: [],
    subunit: 'piaster',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '&#x00A3;',
    decimal: '.',
    separator: ',',
    isoNumeric: '728',
    smallestDenomination: 5,
  },
  std: {
    priority: 100,
    isoCode: 'STD',
    name: 'São Tomé and Príncipe Dobra',
    symbol: 'Db',
    alternateSymbols: [],
    subunit: 'Cêntimo',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '678',
    smallestDenomination: 10000,
  },
  stn: {
    priority: 100,
    isoCode: 'STN',
    name: 'São Tomé and Príncipe Second Dobra',
    symbol: 'Db',
    disambiguateSymbol: 'STN',
    alternateSymbols: [],
    subunit: 'Cêntimo',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '930',
    smallestDenomination: 10,
  },
  svc: {
    priority: 100,
    isoCode: 'SVC',
    name: 'Salvadoran Colón',
    symbol: '₡',
    alternateSymbols: ['¢'],
    subunit: 'Centavo',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#x20A1;',
    decimal: '.',
    separator: ',',
    isoNumeric: '222',
    smallestDenomination: 1,
  },
  syp: {
    priority: 100,
    isoCode: 'SYP',
    name: 'Syrian Pound',
    symbol: '£S',
    alternateSymbols: ['£', 'ل.س', 'LS', 'الليرة السورية'],
    subunit: 'Piastre',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '&#x00A3;',
    decimal: '.',
    separator: ',',
    isoNumeric: '760',
    smallestDenomination: 100,
  },
  szl: {
    priority: 100,
    isoCode: 'SZL',
    name: 'Swazi Lilangeni',
    symbol: 'E',
    disambiguateSymbol: 'SZL',
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '748',
    smallestDenomination: 1,
  },
  thb: {
    priority: 100,
    isoCode: 'THB',
    name: 'Thai Baht',
    symbol: '฿',
    alternateSymbols: [],
    subunit: 'Satang',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#x0E3F;',
    decimal: '.',
    separator: ',',
    isoNumeric: '764',
    smallestDenomination: 1,
  },
  tjs: {
    priority: 100,
    isoCode: 'TJS',
    name: 'Tajikistani Somoni',
    symbol: 'ЅМ',
    alternateSymbols: [],
    subunit: 'Diram',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '972',
    smallestDenomination: 1,
  },
  tmt: {
    priority: 100,
    isoCode: 'TMT',
    name: 'Turkmenistani Manat',
    symbol: 'T',
    alternateSymbols: [],
    subunit: 'Tenge',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '934',
    smallestDenomination: 1,
  },
  tnd: {
    priority: 100,
    isoCode: 'TND',
    name: 'Tunisian Dinar',
    symbol: 'د.ت',
    alternateSymbols: ['TD', 'DT'],
    subunit: 'Millime',
    subunitToUnit: 1000,
    precision: 3,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '788',
    smallestDenomination: 10,
  },
  top: {
    priority: 100,
    isoCode: 'TOP',
    name: 'Tongan Paʻanga',
    symbol: 'T$',
    alternateSymbols: ['PT'],
    subunit: 'Seniti',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '776',
    smallestDenomination: 1,
  },
  try: {
    priority: 100,
    isoCode: 'TRY',
    name: 'Turkish Lira',
    symbol: '₺',
    alternateSymbols: ['TL'],
    subunit: 'kuruş',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#8378;',
    decimal: ',',
    separator: '.',
    isoNumeric: '949',
    smallestDenomination: 1,
  },
  ttd: {
    priority: 100,
    isoCode: 'TTD',
    name: 'Trinidad and Tobago Dollar',
    symbol: '$',
    disambiguateSymbol: 'TT$',
    alternateSymbols: ['TT$'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '$',
    decimal: '.',
    separator: ',',
    isoNumeric: '780',
    smallestDenomination: 1,
  },
  twd: {
    priority: 100,
    isoCode: 'TWD',
    name: 'New Taiwan Dollar',
    symbol: '$',
    disambiguateSymbol: 'NT$',
    alternateSymbols: ['NT$'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '$',
    decimal: '.',
    separator: ',',
    isoNumeric: '901',
    smallestDenomination: 50,
  },
  tzs: {
    priority: 100,
    isoCode: 'TZS',
    name: 'Tanzanian Shilling',
    symbol: 'Sh',
    alternateSymbols: [],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '834',
    smallestDenomination: 5000,
  },
  uah: {
    priority: 100,
    isoCode: 'UAH',
    name: 'Ukrainian Hryvnia',
    symbol: '₴',
    alternateSymbols: [],
    subunit: 'Kopiyka',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '&#x20B4;',
    decimal: '.',
    separator: ',',
    isoNumeric: '980',
    smallestDenomination: 1,
  },
  ugx: {
    priority: 100,
    isoCode: 'UGX',
    name: 'Ugandan Shilling',
    symbol: 'USh',
    alternateSymbols: [],
    subunit: 'Cent',
    subunitToUnit: 1,
    precision: 0,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '800',
    smallestDenomination: 1000,
  },
  usd: {
    priority: 1,
    isoCode: 'USD',
    name: 'United States Dollar',
    symbol: '$',
    disambiguateSymbol: 'US$',
    alternateSymbols: ['US$'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '$',
    decimal: '.',
    separator: ',',
    isoNumeric: '840',
    smallestDenomination: 1,
  },
  uyu: {
    priority: 100,
    isoCode: 'UYU',
    name: 'Uruguayan Peso',
    symbol: '$U',
    alternateSymbols: ['$U'],
    subunit: 'Centésimo',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '$U',
    decimal: ',',
    separator: '.',
    isoNumeric: '858',
    smallestDenomination: 100,
  },
  uzs: {
    priority: 100,
    isoCode: 'UZS',
    name: 'Uzbekistan Som',
    symbol: "so'm",
    alternateSymbols: ['so‘m', 'сўм', 'сум', 's', 'с'],
    subunit: 'Tiyin',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '860',
    smallestDenomination: 100,
  },
  ves: {
    priority: 100,
    isoCode: 'VES',
    name: 'Venezuelan Bolívar Soberano',
    symbol: 'Bs',
    alternateSymbols: ['Bs.S'],
    subunit: 'Céntimo',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '',
    decimal: ',',
    separator: '.',
    isoNumeric: '928',
    smallestDenomination: 1,
  },
  vnd: {
    priority: 100,
    isoCode: 'VND',
    name: 'Vietnamese Đồng',
    symbol: '₫',
    alternateSymbols: [],
    subunit: 'Hào',
    subunitToUnit: 1,
    precision: 0,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '&#x20AB;',
    decimal: ',',
    separator: '.',
    isoNumeric: '704',
    smallestDenomination: 100,
  },
  vuv: {
    priority: 100,
    isoCode: 'VUV',
    name: 'Vanuatu Vatu',
    symbol: 'Vt',
    alternateSymbols: [],
    subunit: null,
    subunitToUnit: 1,
    precision: 0,
    symbolFirst: true,
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '548',
    smallestDenomination: 1,
  },
  wst: {
    priority: 100,
    isoCode: 'WST',
    name: 'Samoan Tala',
    symbol: 'T',
    disambiguateSymbol: 'WS$',
    alternateSymbols: ['WS$', 'SAT', 'ST'],
    subunit: 'Sene',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '882',
    smallestDenomination: 10,
  },
  xaf: {
    priority: 100,
    isoCode: 'XAF',
    name: 'Central African Cfa Franc',
    symbol: 'CFA',
    disambiguateSymbol: 'FCFA',
    alternateSymbols: ['FCFA'],
    subunit: 'Centime',
    subunitToUnit: 1,
    precision: 0,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '950',
    smallestDenomination: 100,
  },
  xag: {
    priority: 100,
    isoCode: 'XAG',
    name: 'Silver (Troy Ounce)',
    symbol: 'oz t',
    disambiguateSymbol: 'XAG',
    alternateSymbols: [],
    subunit: 'oz',
    subunitToUnit: 1,
    precision: 0,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '961',
  },
  xau: {
    priority: 100,
    isoCode: 'XAU',
    name: 'Gold (Troy Ounce)',
    symbol: 'oz t',
    disambiguateSymbol: 'XAU',
    alternateSymbols: [],
    subunit: 'oz',
    subunitToUnit: 1,
    precision: 0,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '959',
  },
  xba: {
    priority: 100,
    isoCode: 'XBA',
    name: 'European Composite Unit',
    symbol: '',
    disambiguateSymbol: 'XBA',
    alternateSymbols: [],
    subunit: '',
    subunitToUnit: 1,
    precision: 0,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '955',
  },
  xbb: {
    priority: 100,
    isoCode: 'XBB',
    name: 'European Monetary Unit',
    symbol: '',
    disambiguateSymbol: 'XBB',
    alternateSymbols: [],
    subunit: '',
    subunitToUnit: 1,
    precision: 0,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '956',
  },
  xbc: {
    priority: 100,
    isoCode: 'XBC',
    name: 'European Unit of Account 9',
    symbol: '',
    disambiguateSymbol: 'XBC',
    alternateSymbols: [],
    subunit: '',
    subunitToUnit: 1,
    precision: 0,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '957',
  },
  xbd: {
    priority: 100,
    isoCode: 'XBD',
    name: 'European Unit of Account 17',
    symbol: '',
    disambiguateSymbol: 'XBD',
    alternateSymbols: [],
    subunit: '',
    subunitToUnit: 1,
    precision: 0,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '958',
  },
  xcd: {
    priority: 100,
    isoCode: 'XCD',
    name: 'East Caribbean Dollar',
    symbol: '$',
    disambiguateSymbol: 'EX$',
    alternateSymbols: ['EC$'],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '$',
    decimal: '.',
    separator: ',',
    isoNumeric: '951',
    smallestDenomination: 1,
  },
  xdr: {
    priority: 100,
    isoCode: 'XDR',
    name: 'Special Drawing Rights',
    symbol: 'SDR',
    alternateSymbols: ['XDR'],
    subunit: '',
    subunitToUnit: 1,
    precision: 0,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '$',
    decimal: '.',
    separator: ',',
    isoNumeric: '960',
  },
  xof: {
    priority: 100,
    isoCode: 'XOF',
    name: 'West African Cfa Franc',
    symbol: 'Fr',
    disambiguateSymbol: 'CFA',
    alternateSymbols: ['CFA'],
    subunit: 'Centime',
    subunitToUnit: 1,
    precision: 0,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '952',
    smallestDenomination: 100,
  },
  xpd: {
    priority: 100,
    isoCode: 'XPD',
    name: 'Palladium',
    symbol: 'oz t',
    disambiguateSymbol: 'XPD',
    alternateSymbols: [],
    subunit: 'oz',
    subunitToUnit: 1,
    precision: 0,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '964',
  },
  xpf: {
    priority: 100,
    isoCode: 'XPF',
    name: 'Cfp Franc',
    symbol: 'Fr',
    alternateSymbols: ['F'],
    subunit: 'Centime',
    subunitToUnit: 1,
    precision: 0,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '953',
    smallestDenomination: 100,
  },
  xpt: {
    priority: 100,
    isoCode: 'XPT',
    name: 'Platinum',
    symbol: 'oz t',
    alternateSymbols: [],
    subunit: '',
    subunitToUnit: 1,
    precision: 0,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '962',
    smallestDenomination: '',
  },
  xts: {
    priority: 100,
    isoCode: 'XTS',
    name: 'Codes specifically reserved for testing purposes',
    symbol: '',
    alternateSymbols: [],
    subunit: '',
    subunitToUnit: 1,
    precision: 0,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '963',
    smallestDenomination: '',
  },
  yer: {
    priority: 100,
    isoCode: 'YER',
    name: 'Yemeni Rial',
    symbol: '﷼',
    alternateSymbols: [],
    subunit: 'Fils',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '&#xFDFC;',
    decimal: '.',
    separator: ',',
    isoNumeric: '886',
    smallestDenomination: 100,
  },
  zar: {
    priority: 100,
    isoCode: 'ZAR',
    name: 'South African Rand',
    symbol: 'R',
    alternateSymbols: [],
    subunit: 'Cent',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '&#x0052;',
    decimal: '.',
    separator: ',',
    isoNumeric: '710',
    smallestDenomination: 10,
  },
  zmk: {
    priority: 100,
    isoCode: 'ZMK',
    name: 'Zambian Kwacha',
    symbol: 'ZK',
    disambiguateSymbol: 'ZMK',
    alternateSymbols: [],
    subunit: 'Ngwee',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: false,
    format: '%n %u',
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '894',
    smallestDenomination: 5,
  },
  zmw: {
    priority: 100,
    isoCode: 'ZMW',
    name: 'Zambian Kwacha',
    symbol: 'K',
    disambiguateSymbol: 'ZMW',
    alternateSymbols: [],
    subunit: 'Ngwee',
    subunitToUnit: 100,
    precision: 2,
    symbolFirst: true,
    htmlEntity: '',
    decimal: '.',
    separator: ',',
    isoNumeric: '967',
    smallestDenomination: 5,
  },
};
